/*
* Generated file
*
* Generated from: yang module name: learning-switch-impl yang module local name: learning-switch-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Fri Jun 05 11:08:20 PDT 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.sdnhub.odl.tutorial.learningswitch.impl;
public class TutorialLearningSwitchModuleFactory extends org.sdnhub.odl.tutorial.learningswitch.impl.AbstractTutorialLearningSwitchModuleFactory {

}
