/*
* Generated file
*
* Generated from: yang module name: tapapp-impl yang module local name: tapapp-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Fri Jun 05 14:58:22 PDT 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.sdnhub.odl.tutorial.tapapp.impl;
public class TutorialTapAppModuleFactory extends AbstractTutorialTapAppModuleFactory {

}
