/*
* Generated file
*
* Generated from: yang module name: netconf-exercise-impl yang module local name: netconf-exercise-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Mon Aug 31 22:01:26 PDT 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.sdnhub.odl.tutorial.netconf.exercise.impl;
public class TutorialNetconfExerciseModuleFactory extends org.sdnhub.odl.tutorial.netconf.exercise.impl.AbstractTutorialNetconfExerciseModuleFactory {

}
