/*
* Generated file
*
* Generated from: yang module name: acl-impl yang module local name: acl-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Sun Jul 26 00:55:52 PDT 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.sdnhub.odl.tutorial.acl.impl;
public class TutorialACLModuleFactory extends org.sdnhub.odl.tutorial.acl.impl.AbstractTutorialACLModuleFactory {

}
